version: '2'

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /srv/dev-disk-by-uuid-aa01a7c9-fa34-4bd7-bf8b-addf072bcb0c/docker/data/NextCloud/Nextcloud_Database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=OQMvwR69JqPYeESmY52W
      - MYSQL_PASSWORD=08zz3WxvNyxnoyM1IdYf
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 88:80
    depends_on:
      - db
    links:
      - db
    volumes:
      - /srv/dev-disk-by-uuid-aa01a7c9-fa34-4bd7-bf8b-addf072bcb0c/docker/data/NextCloud/Nextcloud_Application:/var/www/html
    environment:
      - MYSQL_PASSWORD=08zz3WxvNyxnoyM1IdYf
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
